feat(content-utils): Add module to retrieve Git times for collection entries
Fryuni/inox-tools pull request #111
Opened 2024-06-06 05:16 UTC by Fryuni

2024-06-15 19:39 UTC, BryceRussell requested changes
I tried previewing this locally, but the example project is giving me this error:

> Cannot find module '@it-astro:content/git' imported from 'C:/Users/Bryce/Desktop/Projects/Astro/inox-tools/examples/content-injection/src/pages/index.astro'

2024-06-15 19:39 UTC, BryceRussell commented on packages/content-utils/src/integration/gitTimePlugin.ts
> +console.log('This is also running');
```suggestion
setContentPath(${JSON.stringify(contentPath)});
```

2024-06-15 19:39 UTC, BryceRussell commented on packages/content-utils/src/integration/gitTimePlugin.ts
> +		console.log(trackedFiles);
```suggestion
```

2024-06-15 19:39 UTC, BryceRussell commented on docs/src/content/docs/content-utils/git-time.mdx
> +   ---
This example could also show that it is possible to do this: `await getOldestCommitDate(entry)`

2024-06-15 19:46 UTC, Fryuni commented
> I tried previewing this locally, but the example project is giving me this error:

Maybe you haven't built the lib with the new code. Try running `pnpm -w build:examples`, it builds the dependencies before building the examples.

2024-06-15 19:58 UTC, BryceRussell commented
I got it working :smile: I did build it, not sure why it broke because all I did was re-run my commands

2024-06-15 19:58 UTC, BryceRussell approved these changes
LGTM!

2024-06-16 20:07 UTC, OliverSpeir approved these changes
🎉

2024-06-17 07:07 UTC, florian-lefebvre approved these changes

2024-06-17 17:59 UTC, merged