feat: New test package
Fryuni/inox-tools pull request #158
Opened 2024-09-05 00:11 UTC by Fryuni

2024-09-05 12:55 UTC, florian-lefebvre requested changes
Haven't reviewed the PR but I think there's work done by Alex to have `astro/test-utils`. I'm afraid this package would be made useless by his work. Let's double check first!

2024-09-06 21:31 UTC, Fryuni commented
There is ongoing conversation about having this in the Astro core repo to be published under `@astrojs/`.

I'll still need this to test existing and future Inox Tools packages until that lands on Astro. If/when that happens, this package can be deprecated.

2024-09-07 06:31 UTC, dreyfus92 reviewed
This is amazing, I left a couple of suggestions to improve clarity. Let me know what you think 😁

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +The final config passed to [Astro's programatic CLI entrypoints](https://docs.astro.build/en/reference/cli-reference/#advanced-apis-experimental). This configuration can be overriden on each method c
```suggestion
The final config passed to [Astro's programatic CLI entrypoints](https://docs.astro.build/en/reference/cli-reference/#advanced-apis-experimental). This configuration can be overridden for each method call.
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +Will be automatically passed to the methods below:
```suggestion
It will automatically be passed to the following methods:
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +Starts a dev server at an available port.
```suggestion
Starts a development server on an available port.
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +This server can't be running at the same time for thein same fixture as .preview() since they share ports.
```suggestion
This server cannot run simultaneously with `.preview()` for the same fixture, as they share ports. Ensure `devServer.stop()` is called before the test exits.
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +Be sure to call devServer.stop() before test exit.
```suggestion
Ensure `devServer.stop()` is called before the test exits.
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +This server can't be running at the same time for thein same fixture as .dev() since they share ports.
```suggestion
This server cannot run simultaneously with `.dev()` on the same fixture, as they share ports.
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +Be sure to call server.stop() before test exit.
```suggestion
Ensure `server.stop()` is called before the test exits.
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +This is a convenience wrapper around [readdir from Node's FS Promise API](https://nodejs.org/api/fs.html#fspromisesreaddirpath-options).
```suggestion
This is a convenience wrapper for [readdir from Node's FS Promise API](https://nodejs.org/api/fs.html#fspromisesreaddirpath-options).
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +A minimal proxy to the underlying Astro App using the test adapter.
```suggestion
A minimal proxy for the underlying Astro app, provided by the test adapter.
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +A Vite plugin to ensure no module in the final bundle relies on the built-in Node modules.
```suggestion
A Vite plugin that ensures no module in the final bundle depends on built-in Node modules.
```

2024-09-07 06:31 UTC, dreyfus92 commented on docs/src/content/docs/astro-tests.mdx
> +If the generated bundle contains any reference to a Node module the build will fail.
```suggestion
If any reference to a Node module is found in the generated bundle, the build will fail.
```

2024-09-10 02:19 UTC, Fryuni commented
I will merge this to proceed with testing everything on Inox Tools. We can always come back to it as others develop opinions about it.

2024-09-10 02:20 UTC, merged